DS-4399: Cache apt packages

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -49,6 +49,40 @@ workflows:
               only:
                 - master
 
+  pre:
+    # https://discuss.circleci.com/t/caching-apt-get-packages/9076
+    - sudo mv /etc/apt/sources.list.d /etc/apt/sources.list.d.save
+    - sudo mkdir /etc/apt/sources.list.d
+    - |
+      sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
+      wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | \
+      sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
+      sudo add-apt-repository -y "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
+      sudo add-apt-repository -y ppa:c2d4u.team/c2d4u4.0+
+
+    # Make the cache dir if it doesn't exist
+    - |
+      if ! [[ -d ../vendor/apt ]]; then
+        mkdir -p ../vendor/apt
+      fi
+
+    # Install R if it doesn't exist
+    - |
+      if [[ ! -e /usr/bin/R ]]; then
+        if ! [[ -d ../vendor/apt/archives ]]; then
+          sudo apt-get update && sudo apt-get install --download-only -y ccache pandoc \
+          libgit2-dev libharfbuzz-dev libfribidi-dev libprotoc-dev libprotobuf-dev \
+          libv8-dev librsvg2-dev libmpfr-dev libnlopt-dev libgdal-dev libproj-dev \
+          r-base r-cran-devtools software-properties-common dirmngr
+          sudo cp -R /var/cache/apt ../vendor/
+          # Making sure our user has ownership, in order to cache
+          sudo chown -R ubuntu:ubuntu ../vendor/apt
+        fi
+
+        # Install all packages in the cache
+        sudo dpkg -i ../vendor/apt/archives/*.deb
+      fi
+
 jobs:
   build-and-check-package:
     executor: default
@@ -70,7 +104,7 @@ jobs:
       # are not picked up by the cache, therefore this workaround is needed.
       # See https://discuss.circleci.com/t/cannot-use-circle-yml-environment-variables-in-cache-keys/10994/7
       - run: echo "$(Rscript -e 'cat(format(getRversion()))')" > /tmp/R_version
-      - run: echo "v2" > /tmp/cache_vers  # Increment this to invalidate cache
+      - run: echo "v3" > /tmp/cache_vers  # Increment this to invalidate cache
       - restore_cache:
           key: R-package-library-{{ checksum "/tmp/cache_vers" }}-{{ checksum "/tmp/R_version" }}
 
@@ -78,15 +112,6 @@ jobs:
       - run:
           name: "Install dependencies"
           command: |
-            sudo apt update -qq
-            sudo apt install -y software-properties-common dirmngr
-            sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
-            wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
-            sudo add-apt-repository -y "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
-            sudo add-apt-repository -y ppa:c2d4u.team/c2d4u4.0+
-            sudo apt update && sudo apt install -y ccache pandoc libgit2-dev libharfbuzz-dev \
-            libfribidi-dev libprotoc-dev libprotobuf-dev libv8-dev librsvg2-dev libmpfr-dev \
-            libnlopt-dev libgdal-dev libproj-dev r-base r-cran-devtools
             sudo bash -c 'cd /usr/local/bin; curl -L https://aka.ms/downloadazcopy-v10-linux | \
             tar --strip-components=1 --exclude=*.txt -xzvf -; chmod +x azcopy'
             R -q -e 'if (!dir.exists("~/R/library")) dir.create("~/R/library", recursive = TRUE)'
@@ -101,6 +126,7 @@ jobs:
           key: R-package-library-{{ checksum "/tmp/cache_vers" }}-{{ checksum "/tmp/R_version" }}
           paths:
             - ../R/library
+            - ../vendor/apt
 
       - run:
           name: "Check package"
@@ -148,15 +174,7 @@ jobs:
           name: "Set environment variables"
           command: |
             echo "$(R -q -e 'cat(format(getRversion()))')" > /tmp/R_version
-            echo "v2" > /tmp/cache_vers  # Increment this to invalidate cache
-            sudo apt update -qq && sudo apt install -y software-properties-common dirmngr
-            sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
-            wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
-            sudo add-apt-repository -y "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
-            sudo add-apt-repository -y ppa:c2d4u.team/c2d4u4.0+
-            sudo apt update && sudo apt install -y ccache pandoc libgit2-dev libharfbuzz-dev \
-            libfribidi-dev libprotoc-dev libprotobuf-dev libv8-dev librsvg2-dev libmpfr-dev \
-            libnlopt-dev libgdal-dev libproj-dev r-base r-cran-devtools
+            echo "v3" > /tmp/cache_vers  # Increment this to invalidate cache
             sudo bash -c 'cd /usr/local/bin; curl -L https://aka.ms/downloadazcopy-v10-linux | \
             tar --strip-components=1 --exclude=*.txt -xzvf -; chmod +x azcopy'
             echo -e ".libPaths(c('$HOME/R/library', '/usr/lib/R/site-library', '/usr/lib/R/library'))" | \
