DS-4521: More fixes to indentation

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -38,31 +38,31 @@ orbs:
       install_apt_packages:
         description: "Download apt dependencies"
         steps:
-          run:
-            command: |
-              sudo mv /etc/apt/sources.list.d /etc/apt/sources.list.d.save
-              sudo mkdir /etc/apt/sources.list.d
-              sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
-              wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | \
-              sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
-              sudo add-apt-repository -y "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
-              sudo add-apt-repository -y ppa:c2d4u.team/c2d4u4.0+
-              # Make the cache dir if it doesn't exist
-              if ! [[ -d ../vendor/apt ]]; then
-                mkdir -p ../vendor/apt
-              fi
-              # Install R if it doesn't exist
-              if ! [ -x "$(command -v R)" ]; then
-                if ! [[ -d ../vendor/apt/archives ]]; then
-                  sudo apt-get update && sudo apt-get install --download-only -y ccache pandoc \
-                  libgit2-dev libharfbuzz-dev libfribidi-dev libprotoc-dev libprotobuf-dev \
-                  libv8-dev librsvg2-dev libmpfr-dev libnlopt-dev libgdal-dev libproj-dev \
-                  r-base r-cran-devtools software-properties-common dirmngr
-                  sudo cp -R /var/cache/apt ../vendor/
-                  # Making sure our user has ownership, in order to cache
-                  sudo chown -R ubuntu:ubuntu ../vendor/apt
+          - run:
+              command: |
+                sudo mv /etc/apt/sources.list.d /etc/apt/sources.list.d.save
+                sudo mkdir /etc/apt/sources.list.d
+                sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
+                wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | \
+                sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
+                sudo add-apt-repository -y "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
+                sudo add-apt-repository -y ppa:c2d4u.team/c2d4u4.0+
+                # Make the cache dir if it doesn't exist
+                if ! [[ -d ../vendor/apt ]]; then
+                  mkdir -p ../vendor/apt
                 fi
-              fi
+                # Install R if it doesn't exist
+                if ! [ -x "$(command -v R)" ]; then
+                  if ! [[ -d ../vendor/apt/archives ]]; then
+                    sudo apt-get update && sudo apt-get install --download-only -y ccache pandoc \
+                    libgit2-dev libharfbuzz-dev libfribidi-dev libprotoc-dev libprotobuf-dev \
+                    libv8-dev librsvg2-dev libmpfr-dev libnlopt-dev libgdal-dev libproj-dev \
+                    r-base r-cran-devtools software-properties-common dirmngr
+                    sudo cp -R /var/cache/apt ../vendor/
+                    # Making sure our user has ownership, in order to cache
+                    sudo chown -R ubuntu:ubuntu ../vendor/apt
+                  fi
+                fi
       install_deps:
         description: "Install R dependencies"
         parameters:
@@ -75,31 +75,31 @@ orbs:
               type: string
         steps:
           - run:
-            command: |
-              # Install all packages in the cache; https://askubuntu.com/a/1454102
-              if ! [ -x "$(command -v R)" ]; then
-                sudo rm /var/cache/debconf/config.dat
-                sudo dpkg -i ../vendor/apt/archives/*.deb
-              fi
-              sudo bash -c 'cd /usr/local/bin; curl -L https://aka.ms/downloadazcopy-v10-linux | \
-              tar --strip-components=1 --exclude=*.txt -xzvf -; chmod +x azcopy'
-              R -q -e 'if (!dir.exists("~/R/library")) dir.create("~/R/library", recursive = TRUE)'
-              echo -e 'options(Ncpus = 4, repos = structure(c(CRAN = "https://cloud.r-project.org/")))' > $HOME/.Rprofile
-              export R_HOME=`R RHOME`
-              echo -e ".libPaths(c('$HOME/R/library', '/usr/lib/R/site-library', '/usr/lib/R/library'))" | \
-              sudo tee -a $R_HOME/etc/Rprofile.site
-              R -q -e 'remotes::install_github("Displayr/flipDevTools", upgrade = "never")'
-              R -q -e 'options(warn = 2); flipDevTools::InstallDeps( \
-              remote.refs = <<paramters.remote-deps>>, dependencies = TRUE)'
+              command: |
+                # Install all packages in the cache; https://askubuntu.com/a/1454102
+                if ! [ -x "$(command -v R)" ]; then
+                  sudo rm /var/cache/debconf/config.dat
+                  sudo dpkg -i ../vendor/apt/archives/*.deb
+                fi
+                sudo bash -c 'cd /usr/local/bin; curl -L https://aka.ms/downloadazcopy-v10-linux | \
+                tar --strip-components=1 --exclude=*.txt -xzvf -; chmod +x azcopy'
+                R -q -e 'if (!dir.exists("~/R/library")) dir.create("~/R/library", recursive = TRUE)'
+                echo -e 'options(Ncpus = 4, repos = structure(c(CRAN = "https://cloud.r-project.org/")))' > $HOME/.Rprofile
+                export R_HOME=`R RHOME`
+                echo -e ".libPaths(c('$HOME/R/library', '/usr/lib/R/site-library', '/usr/lib/R/library'))" | \
+                sudo tee -a $R_HOME/etc/Rprofile.site
+                R -q -e 'remotes::install_github("Displayr/flipDevTools", upgrade = "never")'
+                R -q -e 'options(warn = 2); flipDevTools::InstallDeps( \
+                remote.refs = <<paramters.remote-deps>>, dependencies = TRUE)'
 
       build_package:
         description: "Build source and binary package"
         steps:
           - run:
-            command: |
-              R CMD build --no-build-vignettes .
-              R CMD INSTALL --build .
-              mkdir built && cp *.tar.gz built/
+              command: |
+                R CMD build --no-build-vignettes .
+                R CMD INSTALL --build .
+                mkdir built && cp *.tar.gz built/
           - persist_to_workspace:
               root: .
               paths:
@@ -205,17 +205,17 @@ orbs:
           - restore_cache:
             key: R-package-library-{{ checksum "./tmp/cache_vers" }}
           - run:
-            name: Setup cache
-            command: |
-              if ! [[ -d tmp ]]; then
-                mkdir tmp
-              fi
-              echo "^tmp" >> .Rbuildignore
-              echo "$(which R | grep -Fvce '/usr/bin/R')" &&
-              echo "$(R -q -e 'cat(format(getRversion()))')" > ./tmp/R_version
-              echo "v0" > ./tmp/cache_vers  # Increment this to invalidate cache
-              git log --format=%B -n 1 $CIRCLE_SHA1 | \
-              grep -Fe '<CLEAR_CACHE>' > ./tmp/cache_vers  
+              name: Setup cache
+              command: |
+                if ! [[ -d tmp ]]; then
+                  mkdir tmp
+                fi
+                echo "^tmp" >> .Rbuildignore
+                echo "$(which R | grep -Fvce '/usr/bin/R')" &&
+                echo "$(R -q -e 'cat(format(getRversion()))')" > ./tmp/R_version
+                echo "v0" > ./tmp/cache_vers  # Increment this to invalidate cache
+                git log --format=%B -n 1 $CIRCLE_SHA1 | \
+                grep -Fe '<CLEAR_CACHE>' > ./tmp/cache_vers  
           # https://discuss.circleci.com/t/caching-apt-get-packages/9076
           - install_apt_packages
           # - update_apt_packages
